apiVersion: v1
kind: Service
metadata:
  name: rest
  labels:
    process: kafka-node
    app: node-kafka
spec:
  ports:
    - port: 3000
      name: rest
  selector:
    app: node-kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-kafka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-kafka
  template:
    metadata:
      labels:
        process: kafka-node
        app: node-kafka
    spec:
      containers:
        - name: node-kafka
          image: krewilone/nodeapp
          ports:
            - containerPort: 3000
          env:
            - name: KAFKA
              value: kafka-0.kafka-headless:9092,kafka-1.kafka-headless:9092,kafka-2.kafka-headless:9092
            - name: ZOOKEEPER
              value: zk-cs:2181
            - name: GROUP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 1