apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumpbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jumpbox
  template:
    metadata:
      labels:
        app: jumpbox
    spec:
      containers:
        - name: jumpbox
          image: radial/busyboxplus:curl
          command: [sh, -c, "sleep 1000"]