apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    process: kafka-node
    app: kafka
spec:
  ports:
    - port: 9092
      name: kafka
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    process: kafka-node
    app: kafka
spec:
  serviceName: kafka-headless
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: kafka
  replicas: 3
  template:
    metadata:
      labels:
        process: kafka-node
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 800Mi
          ports:
            - containerPort: 9092
              name: kafka
          env:
            - name: KAFKA_CREATE_TOPICS
              value: test:3:3,test-topic:3:2
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zk-cs:2181
            - name: BROKER_ID_COMMAND
              value: "echo ${HOSTNAME} | tail -c 2"
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
